export const spanishProvinces = [
  "A Coruna",
  "Alava",
  "Albacete",
  "Alicante",
  "Almeria",
  "Asturias",
  "Avila",
  "Badajoz",
  "Barcelona",
  "Burgos",
  "Caceres",
  "Cadiz",
  "Cantabria",
  "Castellon",
  "Ceuta",
  "Ciudad Real",
  "Cordoba",
  "Cuenca",
  "Girona",
  "Granada",
  "Guadalajara",
  "Gipuzkoa",
  "Huelva",
  "Huesca",
  "Illes Balears",
  "Jaen",
  "La Rioja",
  "Las Palmas",
  "Leon",
  "Lleida",
  "Lugo",
  "Madrid",
  "Malaga",
  "Melilla",
  "Murcia",
  "Navarra",
  "Ourense",
  "Palencia",
  "Pontevedra",
  "Salamanca",
  "Santa Cruz de Tenerife",
  "Segovia",
  "Sevilla",
  "Soria",
  "Tarragona",
  "Teruel",
  "Toledo",
  "Valencia",
  "Valladolid",
  "Bizkaia",
  "Zamora",
  "Zaragoza"
] as const;

const aliases: Record<string, string> = {
  "a coruna": "A Coruna",
  "a coruña": "A Coruna",
  "alava": "Alava",
  "araba": "Alava",
  "almeria": "Almeria",
  "almería": "Almeria",
  "avila": "Avila",
  "ávila": "Avila",
  "caceres": "Caceres",
  "cáceres": "Caceres",
  "cadiz": "Cadiz",
  "cádiz": "Cadiz",
  "castellon": "Castellon",
  "castellón": "Castellon",
  "cordoba": "Cordoba",
  "córdoba": "Cordoba",
  "gerona": "Girona",
  "guipuzcoa": "Gipuzkoa",
  "guipúzcoa": "Gipuzkoa",
  "jaen": "Jaen",
  "jaén": "Jaen",
  "leon": "Leon",
  "león": "Leon",
  "malaga": "Malaga",
  "málaga": "Malaga",
  "orense": "Ourense",
  "vizcaya": "Bizkaia",
  "islas baleares": "Illes Balears",
  "baleares": "Illes Balears",
  "tenerife": "Santa Cruz de Tenerife"
};

export function normalizeProvince(value?: string | null) {
  const raw = String(value || "").trim();
  if (!raw) return "";
  const key = raw.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g, "");
  const direct = spanishProvinces.find(province => province.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g, "") === key);
  return direct || aliases[raw.toLowerCase()] || aliases[key] || raw;
}

export const provinceOptions = ["", ...spanishProvinces];
